---
title: "CBA Symposium: <span style='color: #b52b4c;'><br>An Introduction</span>"
author: "Center for Customer Insights and Digital Marketing"
institute: "Cal Poly Pomona"
date: "04/25/2025"
date-format: "M/D/YYYY"
format:
  revealjs:
    center: false
    logo: "logos/ccidm-cpp logo.png"
    theme: [default, theme.scss]
    slide-number: true
    toc: true
    toc-depth: 1
    code-link: true
    link-external-newwindow: true
    #chalkboard: true #cannot use with self-contained
    embed-resources: true
    multiplex: true
    width: 1600
    height: 900
    margin: 0.1
    minScale: 0.2
    maxScale: 2.0
    scrollable: true
    html:
      unsafe: true
execute: 
  freeze: auto
---

# Greetings and Introductions

-   Jae Jung, Ph.D., Professor of Marketing, Presenter
-   Jarrod Griffin, Master's Student - Digital Marketing, Presenter, Moderator

# Announcement

-   Workshop slide materials available at <https://github.com/CCIDM/cba-symposium-quarto>
-   Live slides available at <https://ccidm.github.io/cba-symposium-quarto>
-   Questions

# Overall Agenda

::: incremental
1.  Greetings and Introduction to Presenters (Moderator)
2.  Announcement (Moderator)
3.  Expected Learning Outcomes & Agenda (Moderator)
4.  Overview of Quarto and reproducible publications (20 min)
    -   Introduction to Quarto
    -   Quarto Formats
    -   Samples of Quarto documents
5.  Publishing a professional portfolio website with Quarto (40 min)
6.  Q&A (5 min)
:::

# Expected Learning outcomes:

After taking this workshop, participants should be able to:

::: {.medium-small .incremental}
1.  Template
2.  
:::

# Publishing a professional portfolio website with Quarto with `Jarrod Griffin`

## Expected Outcomes:

::: {.incremental}
- Walk away with a starter professional website including résumé
- Publish your professional portfolio website
- Customize themeing via SCSS 
- Understand options on linking a custom domain to a freely hosted website
:::

::: {.fragment}
Who here currently has a professional website? 
:::


## Why Quarto for a professional portfolio website?
- **Write once → ship anywhere** (HTML, slides, dashboards) 
- Native **R / Python** for fully reproducible analytics  
- _Examples_: Refer to Dr. Jung’s section  
- Zero-cost hosting: GitHub Pages · Quarto Pub · Netlify 

## Live Example - Quick Tour

<iframe src="https:jarrodgriffin.com" width="100%" height="800"></iframe>


## Hands-On Live Build <br><br>


### Follow along to create your own professional website! Instructions on next slide. Requirements: <br><br>

#### - RStudio installed
#### - Internet connection










# Q&A

-   Open the floor for any questions.

# Thank You!
